
package org.krams.tutorial.oxm;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SubscriptionPortService", targetNamespace = "http://localhost:8080/sprWsFirst/ws/schema/oss", wsdlLocation = "http://localhost:8080/sprWsFirst/krams/ws/subscription.wsdl")
public class SubscriptionPortService
    extends Service
{

    private final static URL SUBSCRIPTIONPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.krams.tutorial.oxm.SubscriptionPortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.krams.tutorial.oxm.SubscriptionPortService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/sprWsFirst/krams/ws/subscription.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/sprWsFirst/krams/ws/subscription.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SUBSCRIPTIONPORTSERVICE_WSDL_LOCATION = url;
    }

    public SubscriptionPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriptionPortService() {
        super(SUBSCRIPTIONPORTSERVICE_WSDL_LOCATION, new QName("http://localhost:8080/sprWsFirst/ws/schema/oss", "SubscriptionPortService"));
    }

    /**
     * 
     * @return
     *     returns SubscriptionPort
     */
    @WebEndpoint(name = "SubscriptionPortSoap11")
    public SubscriptionPort getSubscriptionPortSoap11() {
        return super.getPort(new QName("http://localhost:8080/sprWsFirst/ws/schema/oss", "SubscriptionPortSoap11"), SubscriptionPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriptionPort
     */
    @WebEndpoint(name = "SubscriptionPortSoap11")
    public SubscriptionPort getSubscriptionPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/sprWsFirst/ws/schema/oss", "SubscriptionPortSoap11"), SubscriptionPort.class, features);
    }

}
